[pytest]
testpaths = tests

markers =
    webtest: mark test as a web test
    sampletest: mark test as a sample test
    slow: mark test as slow
    integration: mark test as integration
    smoke: mark test as smoke

addopts = -ra -q

filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning

# Optional: only if you install pytest-timeout
# timeout = 30
